RENAME_DICT = {'HOST CLUB': "hostclub",
               "NAME": "hostclub",
'EVENT NUMBER': "event_number",
'EVENT ADDRESS': "event_address",
"ADDRESS": "event_address",
"ADRESS": "event_address",
'CITY': "city",
'STATE': "state",
'STTE': "state",
'TIME ZONE': "timezone",
"TIME XONE": "timezone",
'ELIGIBLE BREEDS': "eligible_breeds",
'ENTRY FEE': "entry_fee",
'EVENT TYPE': "event_type",
"Event Type": "event_type",
'EVENT START DATE': "start_date",
"EVENT START & FINISH  DATES": "start_date",
"EVENT START & FINISH DATES":"start_date",
# "closing_date",
'EVENT START DAY': "start_day",
"EVENT START & FINISH DAYS": "start_day",
# "closing_day",
'EVENT CHAIRPERSON': "chairperson",
"EVENT CHAIR PERSON": "chairperson",
'EVENT CHAIR EMAIL': "chairperson_email",
'EVENT CHAIR PHONE': "chairperson_phone",
}

server = "prod"
# server = "local"
