RENAME_DICT = {'HOST CLUB': "hostclub",
               "NAME": "hostclub",
               "HOST CLUB EVENT": "hostclub",
'EVENT NUMBER': "event_number",
'EVENT ADDRESS': "event_address",
"ADDRESS": "event_address",
"ADRESS": "event_address",
'CITY': "city",
'STATE': "state",
'STTE': "state",
'TIME ZONE': "timezone",
"TIME XONE": "timezone",
'ELIGIBLE BREEDS': "eligible_breeds",
'ENTRY FEE': "entry_fee",
'EVENT TYPE': "event_type",
"Event Type": "event_type",
'EVENT START DATE': "start_date",
"EVENT START & FINISH  DATES": "start_date",
"EVENT START & FINISH DATES":"start_date",
# "closing_date",
'EVENT START DAY': "start_day",
"EVENT START & FINISH DAYS": "start_day",
# "closing_day",
'EVENT CHAIRPERSON': "chairperson",

"EVENT CONTACTSecretary Name":  "chairperson",
"EVENT CONTACT":  "chairperson",
"EVENT CHAIR PERSON": "chairperson",
"EVENT CONTACT": "chairperson",
'EVENT CHAIR EMAIL': "chairperson_email",
"CONTACT EMAIL": "chairperson_email",
"EVENT CONTACT EMAIL": "chairperson_email",
'EVENT CHAIR PHONE': "chairperson_phone",
"EVENT CONTACT PHONE":  "chairperson_phone",
"CONTACT PHONE":  "chairperson_phone",

}



CLUB_RENAME_DICT = {
    "club_number": "clubNumber",
    "clubnumber": "clubNumber",
    "club_name": "clubName",
    "clubname": "clubName",
    "club_type": "clubType",
    "clubtype": "clubType",
    "secretary_role": "secretaryRole",
    "secretaryrole": "secretaryRole",
    "secretary_name": "secretaryName",
    "secretaryname": "secretaryName",
    "secretary_email": "secretaryEmail",
    "secretaryemail": "secretaryEmail",
    "state_name": "stateName",
    "statename": "stateName",
    "state_code": "stateCode",
    "statecode": "stateCode",
    "event_type": "eventType",
    "eventtype": "eventType",
    "street address": "address",
    "Street address": "address",
    "Street Address": "address",
    "city": "StateName",
    "City": "StateName",
    
}


server = "prod"
# server = "local"
